// Generated by gencpp from file waypoint_navigation/goToWaypointGoal.msg
// DO NOT EDIT!


#ifndef WAYPOINT_NAVIGATION_MESSAGE_GOTOWAYPOINTGOAL_H
#define WAYPOINT_NAVIGATION_MESSAGE_GOTOWAYPOINTGOAL_H


#include <string>
#include <vector>
#include <map>

#include <ros/types.h>
#include <ros/serialization.h>
#include <ros/builtin_message_traits.h>
#include <ros/message_operations.h>

#include <move_base_msgs/MoveBaseActionGoal.h>

namespace waypoint_navigation
{
template <class ContainerAllocator>
struct goToWaypointGoal_
{
  typedef goToWaypointGoal_<ContainerAllocator> Type;

  goToWaypointGoal_()
    : move_base_goal()  {
    }
  goToWaypointGoal_(const ContainerAllocator& _alloc)
    : move_base_goal(_alloc)  {
  (void)_alloc;
    }



   typedef  ::move_base_msgs::MoveBaseActionGoal_<ContainerAllocator>  _move_base_goal_type;
  _move_base_goal_type move_base_goal;





  typedef boost::shared_ptr< ::waypoint_navigation::goToWaypointGoal_<ContainerAllocator> > Ptr;
  typedef boost::shared_ptr< ::waypoint_navigation::goToWaypointGoal_<ContainerAllocator> const> ConstPtr;

}; // struct goToWaypointGoal_

typedef ::waypoint_navigation::goToWaypointGoal_<std::allocator<void> > goToWaypointGoal;

typedef boost::shared_ptr< ::waypoint_navigation::goToWaypointGoal > goToWaypointGoalPtr;
typedef boost::shared_ptr< ::waypoint_navigation::goToWaypointGoal const> goToWaypointGoalConstPtr;

// constants requiring out of line definition



template<typename ContainerAllocator>
std::ostream& operator<<(std::ostream& s, const ::waypoint_navigation::goToWaypointGoal_<ContainerAllocator> & v)
{
ros::message_operations::Printer< ::waypoint_navigation::goToWaypointGoal_<ContainerAllocator> >::stream(s, "", v);
return s;
}

} // namespace waypoint_navigation

namespace ros
{
namespace message_traits
{



// BOOLTRAITS {'IsFixedSize': False, 'IsMessage': True, 'HasHeader': False}
// {'move_base_msgs': ['/opt/ros/kinetic/share/move_base_msgs/cmake/../msg'], 'geometry_msgs': ['/opt/ros/kinetic/share/geometry_msgs/cmake/../msg'], 'actionlib_msgs': ['/opt/ros/kinetic/share/actionlib_msgs/cmake/../msg'], 'std_msgs': ['/opt/ros/kinetic/share/std_msgs/cmake/../msg'], 'waypoint_navigation': ['/home/elliottwhite/proj515_ws/devel/share/waypoint_navigation/msg']}

// !!!!!!!!!!! ['__class__', '__delattr__', '__dict__', '__doc__', '__eq__', '__format__', '__getattribute__', '__hash__', '__init__', '__module__', '__ne__', '__new__', '__reduce__', '__reduce_ex__', '__repr__', '__setattr__', '__sizeof__', '__str__', '__subclasshook__', '__weakref__', '_parsed_fields', 'constants', 'fields', 'full_name', 'has_header', 'header_present', 'names', 'package', 'parsed_fields', 'short_name', 'text', 'types']




template <class ContainerAllocator>
struct IsFixedSize< ::waypoint_navigation::goToWaypointGoal_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::waypoint_navigation::goToWaypointGoal_<ContainerAllocator> const>
  : FalseType
  { };

template <class ContainerAllocator>
struct IsMessage< ::waypoint_navigation::goToWaypointGoal_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsMessage< ::waypoint_navigation::goToWaypointGoal_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct HasHeader< ::waypoint_navigation::goToWaypointGoal_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct HasHeader< ::waypoint_navigation::goToWaypointGoal_<ContainerAllocator> const>
  : FalseType
  { };


template<class ContainerAllocator>
struct MD5Sum< ::waypoint_navigation::goToWaypointGoal_<ContainerAllocator> >
{
  static const char* value()
  {
    return "527f3c9e12a6914b7e6eb77ae24e5113";
  }

  static const char* value(const ::waypoint_navigation::goToWaypointGoal_<ContainerAllocator>&) { return value(); }
  static const uint64_t static_value1 = 0x527f3c9e12a6914bULL;
  static const uint64_t static_value2 = 0x7e6eb77ae24e5113ULL;
};

template<class ContainerAllocator>
struct DataType< ::waypoint_navigation::goToWaypointGoal_<ContainerAllocator> >
{
  static const char* value()
  {
    return "waypoint_navigation/goToWaypointGoal";
  }

  static const char* value(const ::waypoint_navigation::goToWaypointGoal_<ContainerAllocator>&) { return value(); }
};

template<class ContainerAllocator>
struct Definition< ::waypoint_navigation::goToWaypointGoal_<ContainerAllocator> >
{
  static const char* value()
  {
    return "# ====== DO NOT MODIFY! AUTOGENERATED FROM AN ACTION DEFINITION ======\n\
# Define the goal\n\
move_base_msgs/MoveBaseActionGoal move_base_goal\n\
\n\
================================================================================\n\
MSG: move_base_msgs/MoveBaseActionGoal\n\
# ====== DO NOT MODIFY! AUTOGENERATED FROM AN ACTION DEFINITION ======\n\
\n\
Header header\n\
actionlib_msgs/GoalID goal_id\n\
MoveBaseGoal goal\n\
\n\
================================================================================\n\
MSG: std_msgs/Header\n\
# Standard metadata for higher-level stamped data types.\n\
# This is generally used to communicate timestamped data \n\
# in a particular coordinate frame.\n\
# \n\
# sequence ID: consecutively increasing ID \n\
uint32 seq\n\
#Two-integer timestamp that is expressed as:\n\
# * stamp.sec: seconds (stamp_secs) since epoch (in Python the variable is called 'secs')\n\
# * stamp.nsec: nanoseconds since stamp_secs (in Python the variable is called 'nsecs')\n\
# time-handling sugar is provided by the client library\n\
time stamp\n\
#Frame this data is associated with\n\
# 0: no frame\n\
# 1: global frame\n\
string frame_id\n\
\n\
================================================================================\n\
MSG: actionlib_msgs/GoalID\n\
# The stamp should store the time at which this goal was requested.\n\
# It is used by an action server when it tries to preempt all\n\
# goals that were requested before a certain time\n\
time stamp\n\
\n\
# The id provides a way to associate feedback and\n\
# result message with specific goal requests. The id\n\
# specified must be unique.\n\
string id\n\
\n\
\n\
================================================================================\n\
MSG: move_base_msgs/MoveBaseGoal\n\
# ====== DO NOT MODIFY! AUTOGENERATED FROM AN ACTION DEFINITION ======\n\
geometry_msgs/PoseStamped target_pose\n\
\n\
================================================================================\n\
MSG: geometry_msgs/PoseStamped\n\
# A Pose with reference coordinate frame and timestamp\n\
Header header\n\
Pose pose\n\
\n\
================================================================================\n\
MSG: geometry_msgs/Pose\n\
# A representation of pose in free space, composed of position and orientation. \n\
Point position\n\
Quaternion orientation\n\
\n\
================================================================================\n\
MSG: geometry_msgs/Point\n\
# This contains the position of a point in free space\n\
float64 x\n\
float64 y\n\
float64 z\n\
\n\
================================================================================\n\
MSG: geometry_msgs/Quaternion\n\
# This represents an orientation in free space in quaternion form.\n\
\n\
float64 x\n\
float64 y\n\
float64 z\n\
float64 w\n\
";
  }

  static const char* value(const ::waypoint_navigation::goToWaypointGoal_<ContainerAllocator>&) { return value(); }
};

} // namespace message_traits
} // namespace ros

namespace ros
{
namespace serialization
{

  template<class ContainerAllocator> struct Serializer< ::waypoint_navigation::goToWaypointGoal_<ContainerAllocator> >
  {
    template<typename Stream, typename T> inline static void allInOne(Stream& stream, T m)
    {
      stream.next(m.move_base_goal);
    }

    ROS_DECLARE_ALLINONE_SERIALIZER
  }; // struct goToWaypointGoal_

} // namespace serialization
} // namespace ros

namespace ros
{
namespace message_operations
{

template<class ContainerAllocator>
struct Printer< ::waypoint_navigation::goToWaypointGoal_<ContainerAllocator> >
{
  template<typename Stream> static void stream(Stream& s, const std::string& indent, const ::waypoint_navigation::goToWaypointGoal_<ContainerAllocator>& v)
  {
    s << indent << "move_base_goal: ";
    s << std::endl;
    Printer< ::move_base_msgs::MoveBaseActionGoal_<ContainerAllocator> >::stream(s, indent + "  ", v.move_base_goal);
  }
};

} // namespace message_operations
} // namespace ros

#endif // WAYPOINT_NAVIGATION_MESSAGE_GOTOWAYPOINTGOAL_H
