// Auto-generated. Do not edit!

// (in-package waypoint_navigation.msg)


"use strict";

const _serializer = _ros_msg_utils.Serialize;
const _arraySerializer = _serializer.Array;
const _deserializer = _ros_msg_utils.Deserialize;
const _arrayDeserializer = _deserializer.Array;
const _finder = _ros_msg_utils.Find;
const _getByteLength = _ros_msg_utils.getByteLength;
let move_base_msgs = _finder('move_base_msgs');

//-----------------------------------------------------------

class goToWaypointGoal {
  constructor(initObj={}) {
    if (initObj === null) {
      // initObj === null is a special case for deserialization where we don't initialize fields
      this.move_base_goal = null;
    }
    else {
      if (initObj.hasOwnProperty('move_base_goal')) {
        this.move_base_goal = initObj.move_base_goal
      }
      else {
        this.move_base_goal = new move_base_msgs.msg.MoveBaseActionGoal();
      }
    }
  }

  static serialize(obj, buffer, bufferOffset) {
    // Serializes a message object of type goToWaypointGoal
    // Serialize message field [move_base_goal]
    bufferOffset = move_base_msgs.msg.MoveBaseActionGoal.serialize(obj.move_base_goal, buffer, bufferOffset);
    return bufferOffset;
  }

  static deserialize(buffer, bufferOffset=[0]) {
    //deserializes a message object of type goToWaypointGoal
    let len;
    let data = new goToWaypointGoal(null);
    // Deserialize message field [move_base_goal]
    data.move_base_goal = move_base_msgs.msg.MoveBaseActionGoal.deserialize(buffer, bufferOffset);
    return data;
  }

  static getMessageSize(object) {
    let length = 0;
    length += move_base_msgs.msg.MoveBaseActionGoal.getMessageSize(object.move_base_goal);
    return length;
  }

  static datatype() {
    // Returns string type for a message object
    return 'waypoint_navigation/goToWaypointGoal';
  }

  static md5sum() {
    //Returns md5sum for a message object
    return '527f3c9e12a6914b7e6eb77ae24e5113';
  }

  static messageDefinition() {
    // Returns full string definition for message
    return `
    # ====== DO NOT MODIFY! AUTOGENERATED FROM AN ACTION DEFINITION ======
    # Define the goal
    move_base_msgs/MoveBaseActionGoal move_base_goal
    
    ================================================================================
    MSG: move_base_msgs/MoveBaseActionGoal
    # ====== DO NOT MODIFY! AUTOGENERATED FROM AN ACTION DEFINITION ======
    
    Header header
    actionlib_msgs/GoalID goal_id
    MoveBaseGoal goal
    
    ================================================================================
    MSG: std_msgs/Header
    # Standard metadata for higher-level stamped data types.
    # This is generally used to communicate timestamped data 
    # in a particular coordinate frame.
    # 
    # sequence ID: consecutively increasing ID 
    uint32 seq
    #Two-integer timestamp that is expressed as:
    # * stamp.sec: seconds (stamp_secs) since epoch (in Python the variable is called 'secs')
    # * stamp.nsec: nanoseconds since stamp_secs (in Python the variable is called 'nsecs')
    # time-handling sugar is provided by the client library
    time stamp
    #Frame this data is associated with
    # 0: no frame
    # 1: global frame
    string frame_id
    
    ================================================================================
    MSG: actionlib_msgs/GoalID
    # The stamp should store the time at which this goal was requested.
    # It is used by an action server when it tries to preempt all
    # goals that were requested before a certain time
    time stamp
    
    # The id provides a way to associate feedback and
    # result message with specific goal requests. The id
    # specified must be unique.
    string id
    
    
    ================================================================================
    MSG: move_base_msgs/MoveBaseGoal
    # ====== DO NOT MODIFY! AUTOGENERATED FROM AN ACTION DEFINITION ======
    geometry_msgs/PoseStamped target_pose
    
    ================================================================================
    MSG: geometry_msgs/PoseStamped
    # A Pose with reference coordinate frame and timestamp
    Header header
    Pose pose
    
    ================================================================================
    MSG: geometry_msgs/Pose
    # A representation of pose in free space, composed of position and orientation. 
    Point position
    Quaternion orientation
    
    ================================================================================
    MSG: geometry_msgs/Point
    # This contains the position of a point in free space
    float64 x
    float64 y
    float64 z
    
    ================================================================================
    MSG: geometry_msgs/Quaternion
    # This represents an orientation in free space in quaternion form.
    
    float64 x
    float64 y
    float64 z
    float64 w
    
    `;
  }

  static Resolve(msg) {
    // deep-construct a valid message object instance of whatever was passed in
    if (typeof msg !== 'object' || msg === null) {
      msg = {};
    }
    const resolved = new goToWaypointGoal(null);
    if (msg.move_base_goal !== undefined) {
      resolved.move_base_goal = move_base_msgs.msg.MoveBaseActionGoal.Resolve(msg.move_base_goal)
    }
    else {
      resolved.move_base_goal = new move_base_msgs.msg.MoveBaseActionGoal()
    }

    return resolved;
    }
};

module.exports = goToWaypointGoal;
