; Auto-generated. Do not edit!


(cl:in-package waypoint_navigation-msg)


;//! \htmlinclude cancelWaypointGoal.msg.html

(cl:defclass <cancelWaypointGoal> (roslisp-msg-protocol:ros-message)
  ((move_base_cancel_goal
    :reader move_base_cancel_goal
    :initarg :move_base_cancel_goal
    :type actionlib_msgs-msg:GoalID
    :initform (cl:make-instance 'actionlib_msgs-msg:GoalID)))
)

(cl:defclass cancelWaypointGoal (<cancelWaypointGoal>)
  ())

(cl:defmethod cl:initialize-instance :after ((m <cancelWaypointGoal>) cl:&rest args)
  (cl:declare (cl:ignorable args))
  (cl:unless (cl:typep m 'cancelWaypointGoal)
    (roslisp-msg-protocol:msg-deprecation-warning "using old message class name waypoint_navigation-msg:<cancelWaypointGoal> is deprecated: use waypoint_navigation-msg:cancelWaypointGoal instead.")))

(cl:ensure-generic-function 'move_base_cancel_goal-val :lambda-list '(m))
(cl:defmethod move_base_cancel_goal-val ((m <cancelWaypointGoal>))
  (roslisp-msg-protocol:msg-deprecation-warning "Using old-style slot reader waypoint_navigation-msg:move_base_cancel_goal-val is deprecated.  Use waypoint_navigation-msg:move_base_cancel_goal instead.")
  (move_base_cancel_goal m))
(cl:defmethod roslisp-msg-protocol:serialize ((msg <cancelWaypointGoal>) ostream)
  "Serializes a message object of type '<cancelWaypointGoal>"
  (roslisp-msg-protocol:serialize (cl:slot-value msg 'move_base_cancel_goal) ostream)
)
(cl:defmethod roslisp-msg-protocol:deserialize ((msg <cancelWaypointGoal>) istream)
  "Deserializes a message object of type '<cancelWaypointGoal>"
  (roslisp-msg-protocol:deserialize (cl:slot-value msg 'move_base_cancel_goal) istream)
  msg
)
(cl:defmethod roslisp-msg-protocol:ros-datatype ((msg (cl:eql '<cancelWaypointGoal>)))
  "Returns string type for a message object of type '<cancelWaypointGoal>"
  "waypoint_navigation/cancelWaypointGoal")
(cl:defmethod roslisp-msg-protocol:ros-datatype ((msg (cl:eql 'cancelWaypointGoal)))
  "Returns string type for a message object of type 'cancelWaypointGoal"
  "waypoint_navigation/cancelWaypointGoal")
(cl:defmethod roslisp-msg-protocol:md5sum ((type (cl:eql '<cancelWaypointGoal>)))
  "Returns md5sum for a message object of type '<cancelWaypointGoal>"
  "487ad5210dbeac2124197170aef2cfd3")
(cl:defmethod roslisp-msg-protocol:md5sum ((type (cl:eql 'cancelWaypointGoal)))
  "Returns md5sum for a message object of type 'cancelWaypointGoal"
  "487ad5210dbeac2124197170aef2cfd3")
(cl:defmethod roslisp-msg-protocol:message-definition ((type (cl:eql '<cancelWaypointGoal>)))
  "Returns full string definition for message of type '<cancelWaypointGoal>"
  (cl:format cl:nil "# ====== DO NOT MODIFY! AUTOGENERATED FROM AN ACTION DEFINITION ======~%# Cancel the goal~%actionlib_msgs/GoalID move_base_cancel_goal~%~%================================================================================~%MSG: actionlib_msgs/GoalID~%# The stamp should store the time at which this goal was requested.~%# It is used by an action server when it tries to preempt all~%# goals that were requested before a certain time~%time stamp~%~%# The id provides a way to associate feedback and~%# result message with specific goal requests. The id~%# specified must be unique.~%string id~%~%~%~%"))
(cl:defmethod roslisp-msg-protocol:message-definition ((type (cl:eql 'cancelWaypointGoal)))
  "Returns full string definition for message of type 'cancelWaypointGoal"
  (cl:format cl:nil "# ====== DO NOT MODIFY! AUTOGENERATED FROM AN ACTION DEFINITION ======~%# Cancel the goal~%actionlib_msgs/GoalID move_base_cancel_goal~%~%================================================================================~%MSG: actionlib_msgs/GoalID~%# The stamp should store the time at which this goal was requested.~%# It is used by an action server when it tries to preempt all~%# goals that were requested before a certain time~%time stamp~%~%# The id provides a way to associate feedback and~%# result message with specific goal requests. The id~%# specified must be unique.~%string id~%~%~%~%"))
(cl:defmethod roslisp-msg-protocol:serialization-length ((msg <cancelWaypointGoal>))
  (cl:+ 0
     (roslisp-msg-protocol:serialization-length (cl:slot-value msg 'move_base_cancel_goal))
))
(cl:defmethod roslisp-msg-protocol:ros-message-to-list ((msg <cancelWaypointGoal>))
  "Converts a ROS message object to a list"
  (cl:list 'cancelWaypointGoal
    (cl:cons ':move_base_cancel_goal (move_base_cancel_goal msg))
))
